spring:
  application:
    name:config
    
server:
  port:8081
  
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///D://springcloud/
          
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    